### ISSUE TITLE
What Cutters does this code support?

### ISSUE THREAD

**Issue by wholder** [vangdfang/libcutter#13] opened 2019-06-10 19:14 UTC
I'd like to apply this work to a project I'm working on called LaserCut (https://github.com/wholder/LaserCut).  But, it's not cleat to me just exactly what cutter models this code supports.  I assume it's for some Cricut™ models, but which ones?

I also have some questions about the encryption and decryption code and the keys needed to use it.  Can anyone help answer my questions?

Wayne

**Comment by rsaxvc** [comment] 2019-06-23 20:27
We developed it on the original Cricut. I believe it works on others of the same vintage. I haven't and suspect neither of the other devs have kept up with it.

Keys - when we released our software the Cricut owners were going around sueing people under the DMCA, so we explicitly launched without keys.

Here are some keys: http://jimlund.org/build-to-spec/Setting%20Up%20Libcutter%20-%20Cricut%20Hacking%20Wiki.html

It looks like the Cricut company rotated keys at some firmware version once the keys were released, so I'd try with the current keys, avoid upgrading your cutter, and if it doesn't work we may need to recover newer keys.


Sorry for the late response.

**Comment by wholder** [comment] 2019-06-24 03:29
Thanks for your reply.  I've been running some tests on a Cricut Mini and I'm able to get correct responses back from the non-encoded commands, such as mat size, status, etc.  But, I can't get any of the encrypted, movement commands to do work.  I've checked and double-checked my code and verified my XXTEA encode and decode using some pre-encoded messages I found at: https://github.com/vangdfang/libcutter/blob/master/util/test_serial.cpp  I've even tried using different keys for each of the commands to see if they'd been reassigned, but no luck.  The Mini just sits there.

So, I suspect that the Mini uses a different set of keys than the ones you referenced (and which I used in my  code.)  Your message talks about the ability to "recover newer keys", but how is this done?  As far as I know the PICs in the Mini is read protected and the service need to take to the mini and try and capture commands from the USB bus is shut down.  Is there some other method that can recover the keys?

I bought my Mini used, so I don't know if the prior owner updated the firmware, or not, but the value I can read using the 0x12, firmware command is {0x06 0x00 0x1E 0x00 0x00 0x00 0x17} which I think translates to v0.23 with a model number byte of 0x1E.

Wayne

**Comment by rsaxvc** [comment] 2019-06-24 05:18
Wheee, I'll try to remember what I can, but man, this was ~10 years ago.

Ok, it's good that 0x12 works, that indicates they probably didn't change the protocol.

If you have some working desktop software... What OS are you on? On at least Windows and Linux you can hook the USB or Serial stack and record data going through. You might try strace on Linux. On windows maybe process-monitor or portmon?

Once you have sniffed some packets, it should be possible to replay them - and the machine should move the way it moved when the program was in control. I use hexterm https://github.com/rsaxvc/hexterm for interacting in binary with the device.

Then, we sorta need to figure out why libcutter and the original program differ. It's probably the keys. One way you might find the keys is if you were to read the instructions behind the cricut program. If you do so, search for the old keys. You might find the new keys near them.

**Comment by rsaxvc** [comment] 2019-06-24 05:42
http://inspiration.cricut.com/cricut-craft-room-closing/

Wut

**Comment by rsaxvc** [comment] 2019-06-24 06:17
It looks like Cricut has pretty much discontinued and torched all downloads of its old software. Without this it will be very difficult to figure out the Mini's protocol. But also totally worth doing, because the Mini is useless without a desktop to drive it.

**Comment by rsaxvc** [comment] 2019-06-24 06:23
Wheeee https://web.archive.org/web/20130127150559/http://craftroom.cricut.com/betaprogram/cricut-craftroom.exe

**Comment by smonson78** [comment] 2019-06-24 11:52
I'd like to also help out with this if I can. I have a Cricut Expression with firmware 0.23 which doesn't work with libcutter either - I assume the problem is likely to be the same, although I didn't confirm the results of the individual commands the way you have, wholder.

I couldn't install that old copy of Craftroom - I get an error:

```
Sorry, an error has occurred.

The application could not be installed because the installer file 
is damaged. Try obtaining a new installer file from the application author.
```

However, I have the cutter working with an old copy of Sure Cuts A Lot and that might contain the updated keys.

**Comment by wholder** [comment] 2019-06-24 21:50
It's encouraging to hear that the 0.23 firmware does work with Sure Cuts A Lot, as that must mean that someone, somewhere managed to extract the keys.  I'll have to see if I can track down a copy on eBay, or Craigslist.  I do have a Beagle USB analyzerI could use to capture messages, but I have no idea what's involved in trying to extract the keys from messages, as the inclusion of the random word throws a big money wrench into the mix.

I'm also working on adding support to LaserCut for an amazing bit of coding and reverse engineering by Matt Williams (see: [TeensyCNC](https://github.com/seishuku/TeensyCNC)) but it would be nice to be able to use the Mini without having to make hardware mods.  I'd also like to eventually support the older, ATmega1281-based models, but I haven't yet found any for sale that are cheap enough for me to buy.

Wayne

**Comment by smonson78** [comment] 2019-06-24 22:40
It should be possible to capture everything using a purely software serial monitor as described by rsaxvc - but it won't be possible to get the keys from monitoring the encrypted communication. The most likely way to get them will be by finding them in the binaries of a piece of working software.

Sure Cuts A Lot has the same problem as the original Provo Craft software - due to legal action, they had to remove support for the Cricut machines, so only old versions of the software will still work. And it's not possible to buy a legal copy of that old software from them anymore. I will email you about that tonight when I get home from work.

**Comment by rsaxvc** [comment] 2019-06-26 02:28
Strangely, Sure Cuts A Lot uses the same key-set from http://jimlund.org/blog/?p=316 . I'm not sure why @smonson78 's cutter doesn't work with libcutter but does work with SCAL2.

I'm fairly certain the only thing I've tested against was a Cricut Personal.

Do we know the launch dates of early Cricuts? Could it be that encryption was added later and perhaps not needed for the earlier models?

**Comment by wholder** [comment] 2019-06-28 23:46
I haven't made much progress on talking to an unmodified Mini, but I have been able to  successfully modify the Mini's PCB to use [Matt Williams' TeensyCNC project](https://github.com/seishuku/TeensyCNC) and have also updated [LaserCut](https://github.com/wholder/LaserCut) to support it.  The combination seems to work rather well and, in the future,  I may publish a video [on my YouTube channel ](https://www.youtube.com/user/wayneholder)showing how to modify a Mini to run TeensyCNC.  Please let me know if you have any interested in this.

The mod requires unsoldering and removing two PIC ICs on the Mini's PCB, programming a $20 [Teensy 3.2] board (https://www.pjrc.com/store/teensy32.html) with Matt's code, and then soldering about 16 wires from the Teensy to some of the pads of the removed ICs.  Requires patience and decent soldering skills, but not too hard.

Wayne

**Comment by Stegoman** [comment] 2020-02-18 06:04
In the last few weeks I have discovered just how F'd up Provo Craft is.  I was okay being stuck with their web software as I only use my cutter every couple of years.  So, Bingo-Bango, I need my cutter to help my son make posters for his Eagle Scout project and lookie here, my investment in hardware is now worthless!

Hopefully there will continue to be some motion forward so that I can get a bit of use out of my Cricut Expression.  I GUARANTEE you that I will do everything in my power to be sure that buyers AVOID Provo Craft in the future!

The least they could do is release the necessary code to allow us to use the older equipment.  It seems unlikely that anyone that was cutoff like this will be unwilling to buy further from such a despicable company.

Please keep up the great work.  Now to see if I can get this stuff going!

**Comment by citelao** [comment] 2020-08-04 21:49
Though this thread is a bit old, I have been successful running `test_serial` on my Cricut Expression (running version 2.31). I've been working through this protocol in Node/TypeScript because I'm a nutter 😄 .

I had a good deal of frustration with endianness in the TS code, but `test_serial` worked with no modifications whatsoever. [The Python `Cutter` class](http://oscopetutorial.com/cricut/index.php?title=Python) from the wiki was incredibly helpful in this work and includes good stub methods for getting version, mat bounds, and mat presence.

I appreciate the work that has been done on this project, since the other Cricut users in my household would be unhappy if I irrevocably flashed the firmware.

**Comment by ltstein** [comment] 2020-09-29 19:48
> 
> 
> It should be possible to capture everything using a purely software serial monitor as described by rsaxvc - but it won't be possible to get the keys from monitoring the encrypted communication. The most likely way to get them will be by finding them in the binaries of a piece of working software.
> 
> Sure Cuts A Lot has the same problem as the original Provo Craft software - due to legal action, they had to remove support for the Cricut machines, so only old versions of the software will still work. And it's not possible to buy a legal copy of that old software from them anymore. I will email you about that tonight when I get home from work.
@smonson78 
I recently tried to use our old cricut mini and realized they had been EOL'ed and the software completely abandoned. I discovered I had a backup of the installed programs(Craft Room) and some associated drivers from when we last used it much several years ago. Do you think we could salvage the encryption keys from those files somehow? Is there any information on how I might get started with that?

**Comment by rsaxvc** [comment] 2020-12-20 22:27
You would start with a disassembler, then look for any code that loads up the tea/xtra/xxtea(I forget which) constants to try to find the crypto functions. Once you've located those look at functions that call them and try to figure out where they get their keys from.

**Comment by rsaxvc** [comment] 2021-03-26 05:12
The magic number to search for is 0x9e3779b9 or 0xb979379e (it's the first backwards).  You can find it in the btea function from David Wheeler and Roger Needham.

**Comment by citelao** [comment] 2021-04-03 20:41
I can now officially confirm that *at least part* of the protocol works on the Cricut Maker.  I'd be surprised if the keys or the command they use for cutting have not changed. But:

## Version

```
{ modelId: 2049, major: 5, minor: 2559 }
```

## Bounds

```
{ xMin: 5, yMin: 2049, xMax: 17411, yMax: 2559 }
```

Running a cmd40 move command had no effect (though I didn't Start a cutting session)

**Comment by rsaxvc** [comment] 2021-04-05 01:51
Interesting! I think there were some keyed commands(curve and others), and
some unkeyed commands(status and version?).

Do you think the unkeyed commands are working, but not the keyed ones?

**Comment by citelao** [comment] 2021-04-05 15:58
> Do you think the unkeyed commands are working, but not the keyed ones?

I think that's almost exactly the case. `version` and `bounds` and `mat` (/status) are unkeyed (although the Maker was returning that it had a mat despite not having one; I wonder if the semantics have changed).

This also matches what the hacks wiki found [for other cutter models](http://web.archive.org/web/20130501065014/http://www.built-to-spec.com/cricutwiki/index.php?title=Firmware_version):

> Included below are the results for this command from different machines with different firmware versions. The actual version number is identical to the version number displayed when the Cricut model first starts up. (Mini does not have a screen, so it's values are assumed based on the other commands.
>
>The first byte is the number of bytes to expect. The third byte displayed appears to refer to a model identifier, the second byte probably allows for growth. The fifth byte displayed matches the firmware major version, the fourth byte probably allows for growth. The seventh and last byte displayed matches the firmware minor version, the sixth byte probably allows for growth.
>
>Cricut Cake : 20 (v2.34 = 0x0002 0x0022)
>
>Recv: `06 00 14 00 02 00 22`
>
>Cricut Expression : 20 (v2.31 = 0x0002 0x001F)
>
>Recv: 06 00 14 00 02 00 1F
>
>Cricut Mini : 0x1e (v0.23 = 0x0000 0x0017), this may refer to the firmware version of the PIC Microcontroller. The factory firmware version for this specific mini was 19 and the user has upgraded since then.
>
>Recv: `06 00 1e 00 00 00 17`
>
>Cricut Personal : 10 (v1.34 = 0x0001 0x0022)
>
>Recv: `06 00 0a 00 01 00 22`

I'd be surprised if the Maker was still using the encrypted 0x40 command to actually control the cutter:

1. It's slow to cancel
2. Since the command executed is based on the encryption key used, the chance of collision increases really quickly as you have more operations (and the Maker has at least one more, since it has two tool holders [although they may have just introduced a "tool select" command or something]).
3. They definitely have pressure & speed selection commands now, since the app asks what paper you're using.

**Comment by rsaxvc** [comment] 2021-04-06 02:48
The mini would be great to support, since it is abandonware.

Do you know which use a PIC? I only remembered an Atmega128 or something
like that.

**Comment by rsaxvc** [comment] 2021-04-06 03:11
Oh weird, looks like the mini is quite different from the other V1 devices,
two PICs even

**Comment by citelao** [comment] 2021-04-06 03:29
I have scrupulously avoided taking a screwdriver to our Cricuts, on penalty of an angry family 😄. I do not know what's inside our Cricuts.

For what it's worth, I discovered libcutter and the hacking wikis a few months ago. I don't have any background here, unfortunately.

**Comment by rsaxvc** [comment] 2021-04-11 04:07
I found a used one recently, but I'm in the same boat as you - Kate has taking a liking to it. Another is in the mail, but I'm out of town all next week.

Currently, the project scope is first generation devices(Personal, Create, Expression, Cake, Cake Mini). If someone can document the next generation protocols, it should be possible to support them as well. The readme has been updated to list the tested devices.

I'm going to go ahead and close this issue, since I think we have answered the initial query.

Also, big changes coming soon - instead of compiling the magic numbers required for communication with the devices into the library, they'll be moving to a config file thanks to work from @citelao , which will greatly simplify building/testing/operating the library.

**Closed by rsaxvc** 2021-04-11 04:07 UTC
